databases:
  - name: learninglogsdb
    plan: free
    databaseName: learninglogs
    user: learninglogs

services:
  - type: web
    plan: free
    name: learninglogs
    runtime: python
    rootDir: learning_logs
    buildCommand: './build.sh'
    startCommand: gunicorn learning_logs.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learninglogsdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: True
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"