databases:
  - name: learninglogsdb
    plan: free
    databaseName: learninglogs
    user: learninglogs

services:
  - type: web
    plan: free
    name: learninglogs
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn learning_logs.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learninglogsdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4