services:
  - type: web
    name: learning_logs
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn  learning_logss.wsgi:application
    staticPublishPath: staticfiles
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: learning_logs.settings
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
